name: Auto Label Merged PRs

on:
  pull_request:
    types: [closed]

jobs:
  label-merged-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Add hacktoberfest-accepted label to merged PRs
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['hacktoberfest-accepted']
            })
            
            console.log(`Added 'hacktoberfest-accepted' label to merged PR #${context.issue.number}`)
      
      - name: Add comment to merged PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎉 **Congratulations!** This PR has been merged and labeled as `hacktoberfest-accepted`. Thank you for contributing to Profocto! 🚀\n\n**Your contribution counts towards Hacktoberfest 2025!** 🏆'
            })